if(EXISTS "/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_propagator_asteroids_tests[1]_tests.cmake")
  include("/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_propagator_asteroids_tests[1]_tests.cmake")
else()
  add_test(astdyn_propagator_asteroids_tests_NOT_BUILT astdyn_propagator_asteroids_tests_NOT_BUILT)
endif()
