if(EXISTS "/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_pompeja_fit[1]_tests.cmake")
  include("/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_pompeja_fit[1]_tests.cmake")
else()
  add_test(astdyn_pompeja_fit_NOT_BUILT astdyn_pompeja_fit_NOT_BUILT)
endif()
