if(EXISTS "/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_rkf78_debug[1]_tests.cmake")
  include("/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/astdyn_rkf78_debug[1]_tests.cmake")
else()
  add_test(astdyn_rkf78_debug_NOT_BUILT astdyn_rkf78_debug_NOT_BUILT)
endif()
