if(EXISTS "/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/validation_ceres[1]_tests.cmake")
  include("/Users/michelebigi/VisualStudio Code/GitHub/ITALOccultLibrary/astdyn/tests/validation_ceres[1]_tests.cmake")
else()
  add_test(validation_ceres_NOT_BUILT validation_ceres_NOT_BUILT)
endif()
